### Project specific config ###

# Installed for linting the project
language: node_js

matrix:
  include:
    - os: linux
      node_js: "6"
      env: ATOM_CHANNEL=stable

    - os: linux
      node_js: "6"
      env: ATOM_CHANNEL=beta

    - os: osx
      node_js: "6"
      env: ATOM_CHANNEL=stable

env:
  global:
    - ATOM_LINT_WITH_BUNDLED_NODE="false"

### Generic setup follows ###
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

# Needed to disable the auto-install step running `npm install`
install: true

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
